name: Gerar APK EJA Perto de Mim GO

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Compilar aplicativo
        run: gradle assembleDebug --stacktrace

      - name: Renomear APK
        run: |
          mkdir -p release
          cp app/build/outputs/apk/debug/app-debug.apk release/EJA-Perto-de-Mim-GO.apk

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: EJA-Perto-de-Mim-GO
          path: release/EJA-Perto-de-Mim-GO.apk
          if-no-files-found: error
